name: Build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run:  echo "Most nem merem buildizni a minusz pontok miatt"
        #|
       #   chmod +x gradlew
       #   ./gradlew build
